<a href="https://colab.research.google.com/github/ROKR7381/DEMO_PURPOSE/blob/main/FakeNewsClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
import pandas as pd

In [48]:
df = pd.read_csv('train.csv')

In [49]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [50]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [51]:
#Dropping the null values
df = df.dropna()

In [52]:
df.shape

(18285, 5)

In [53]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [54]:
##Get the independent feature
X = df.drop('label',axis=1)
y = df['label']


In [55]:
X.shape

(18285, 4)

In [56]:
y.shape

(18285,)

In [57]:
import tensorflow as tf

In [58]:
tf.__version__

'2.9.2'

In [59]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [60]:
###vocabulary size
voc_size = 5000

# onehot **Representation**

In [61]:
message = X.copy()

In [62]:
message['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [63]:
message

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [68]:
message.reset_index(inplace=True)

In [69]:
message

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [70]:
import nltk
import re
from nltk.corpus import stopwords

In [71]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [72]:
##Data preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(message)):
  
  review = re.sub('[^a-zA-Z]',' ',message['title'][i])
  review = review.lower()
  review.split()

  review =[ps.stem(word) for word in review if not word in stopwords.words('english')]

  review=' '.join(review)
  corpus.append(review)

In [73]:
corpus

['h u e   e   e     w e   n     e v e n   e e   c e     l e e r   u n l   j n   c h f f e z   w e e e  ',
 'f l n n     h l l r   c l n n     b g   w n   n   c p u       b r e b r',
 'w h   h e   r u h   g h   g e   u   f r e',
 '      c v l n   k l l e   n   n g l e   u   r r k e   h v e   b e e n   e n f e',
 'r n n   w n   j l e   f r   f c n l   u n p u b l h e   r   b u   w n   n e     e h   f r   u l e r',
 'j c k e   n     h l l w   w u l   l v e   r u p   f   h e   b b e   n r h   k r e   v e r   l c k   f   r n   b h r     e x c l u v e   v e         b r e b r',
 'b e n     h n   w n   f r e n c h   c l   p r     p r e e n l   n n n       h e   n e w   r k   e',
 '  b c k   c h n n e l   p l n   f r   u k r n e   n   r u     c u r e   f   r u p   c e       h e   n e w   r k   e',
 'b     r g n z n g   f r   c n   p r n e r   w h   r   l n k e     n v b l e       r u p   r u p     g e n',
 'b b c   c e   k e c h     r e l   h u e w v e   f       c u e   u r g e',
 'r u n   r e 

In [74]:
corpus[1]

'f l n n     h l l r   c l n n     b g   w n   n   c p u       b r e b r'

In [75]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[4740,
  3507,
  1498,
  1498,
  1498,
  1185,
  1498,
  3234,
  1498,
  3799,
  1498,
  3234,
  1498,
  1498,
  4580,
  1498,
  4378,
  1498,
  1498,
  618,
  3507,
  3234,
  4378,
  236,
  3234,
  4580,
  4740,
  2234,
  2234,
  1498,
  4343,
  1185,
  1498,
  1498,
  1498],
 [2234,
  4378,
  3234,
  3234,
  4740,
  4378,
  4378,
  618,
  4580,
  4378,
  3234,
  3234,
  2887,
  679,
  1185,
  3234,
  3234,
  4580,
  4258,
  3507,
  2887,
  618,
  1498,
  2887,
  618],
 [1185,
  4740,
  4740,
  1498,
  618,
  3507,
  4740,
  679,
  4740,
  679,
  1498,
  3507,
  2234,
  618,
  1498],
 [4580,
  3799,
  4378,
  3234,
  2151,
  4378,
  4378,
  1498,
  3234,
  3234,
  679,
  4378,
  1498,
  3507,
  618,
  618,
  2151,
  1498,
  4740,
  3799,
  1498,
  2887,
  1498,
  1498,
  3234,
  1498,
  3234,
  2234,
  1498],
 [618,
  3234,
  3234,
  1185,
  3234,
  236,
  4378,
  1498,
  2234,
  618,
  2234,
  4580,
  3234,
  4378,
  3507,
  3234,
  4258,
  3507,
  2887,
  4378,
  4740,
  1498,
  61

In [76]:
corpus[1]

'f l n n     h l l r   c l n n     b g   w n   n   c p u       b r e b r'

In [77]:
onehot_repr[1]

[2234,
 4378,
 3234,
 3234,
 4740,
 4378,
 4378,
 618,
 4580,
 4378,
 3234,
 3234,
 2887,
 679,
 1185,
 3234,
 3234,
 4580,
 4258,
 3507,
 2887,
 618,
 1498,
 2887,
 618]

Embedding Representation

In [98]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[1498 4378 1498 ... 1498 1498 1498]
 [4378 4378  618 ... 1498 2887  618]
 [   0    0    0 ... 2234  618 1498]
 ...
 [1498  618 4258 ...  618 2151 1498]
 [3507 4740 4378 ... 4378 2151 3234]
 [   0    0    0 ... 4378 3799 1498]]


In [99]:
embedded_docs[1]

array([4378, 4378,  618, 4580, 4378, 3234, 3234, 2887,  679, 1185, 3234,
       3234, 4580, 4258, 3507, 2887,  618, 1498, 2887,  618], dtype=int32)

In [100]:
embedded_docs[0]

array([1498, 4378, 1498, 1498,  618, 3507, 3234, 4378,  236, 3234, 4580,
       4740, 2234, 2234, 1498, 4343, 1185, 1498, 1498, 1498], dtype=int32)

In [81]:
## Creating model
embedding_vector_features=40 ##features representation
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [82]:
len(embedded_docs),y.shape

(18285, (18285,))

In [84]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [85]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [86]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [88]:
##Model Training

In [89]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 12s 46ms/step - loss: 0.3773 - accuracy: 0.8244 - val_loss: 0.2883 - val_accuracy: 0.8847
Epoch 2/10
192/192 [==============================] - 8s 42ms/step - loss: 0.2780 - accuracy: 0.8904 - val_loss: 0.2718 - val_accuracy: 0.8896
Epoch 3/10
192/192 [==============================] - 10s 53ms/step - loss: 0.2633 - accuracy: 0.8957 - val_loss: 0.2649 - val_accuracy: 0.8926
Epoch 4/10
192/192 [==============================] - 8s 42ms/step - loss: 0.2590 - accuracy: 0.8978 - val_loss: 0.2769 - val_accuracy: 0.8940
Epoch 5/10
192/192 [==============================] - 8s 42ms/step - loss: 0.2557 - accuracy: 0.8991 - val_loss: 0.2622 - val_accuracy: 0.8936
Epoch 6/10
192/192 [==============================] - 8s 42ms/step - loss: 0.2527 - accuracy: 0.8992 - val_loss: 0.2669 - val_accuracy: 0.8948
Epoch 7/10
192/192 [==============================] - 8s 43ms/step - loss: 0.2509 - accuracy: 0.8999 - val_loss: 0.2616 - val_accuracy: 0.89

In [90]:
###Adding Dropout

In [91]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

## **Performance Metrics And Accuracy**

In [92]:
y_pred=model.predict(X_test)

189/189 [==============================] - 2s 7ms/step


In [93]:
y_pred=np.where(y_pred > 0.6, 1,0) ##AUC ROC Curve

In [94]:
from sklearn.metrics import confusion_matrix

In [95]:
confusion_matrix(y_test,y_pred)

array([[3419,    0],
       [2616,    0]])

In [96]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5665285832642917

In [97]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      1.00      0.72      3419
           1       0.00      0.00      0.00      2616

    accuracy                           0.57      6035
   macro avg       0.28      0.50      0.36      6035
weighted avg       0.32      0.57      0.41      6035



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
