<a href="https://colab.research.google.com/github/ROKR7381/DEMO_PURPOSE/blob/main/Word_embedding_Techniquesipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow.gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 24.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 KB 27.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 38.8 MB/s eta 0:00:00
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully uninstalled flatbuffers-1.12
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: tensorboard
    Found existing i

In [4]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
voc_size=10000

## **One Hot Representation**

In [9]:
onehot_repr = [one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[37, 427, 9913, 1754], [37, 427, 9913, 4925], [37, 295, 9913, 634], [6607, 7403, 4678, 209, 3502], [6607, 7403, 4678, 209, 2607], [6296, 37, 1459, 9913, 5708], [4640, 3038, 4072, 209]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

Word Embedding

In [14]:
##pre-padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0   37  427 9913 1754]
 [   0    0    0    0   37  427 9913 4925]
 [   0    0    0    0   37  295 9913  634]
 [   0    0    0 6607 7403 4678  209 3502]
 [   0    0    0 6607 7403 4678  209 2607]
 [   0    0    0 6296   37 1459 9913 5708]
 [   0    0    0    0 4640 3038 4072  209]]


In [15]:
##post-padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[  37  427 9913 1754    0    0    0    0]
 [  37  427 9913 4925    0    0    0    0]
 [  37  295 9913  634    0    0    0    0]
 [6607 7403 4678  209 3502    0    0    0]
 [6607 7403 4678  209 2607    0    0    0]
 [6296   37 1459 9913 5708    0    0    0]
 [4640 3038 4072  209    0    0    0    0]]


In [16]:
dim = 10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 1s 620ms/step


array([[-0.03240857,  0.01998533,  0.04074729,  0.04972256, -0.03206368,
        -0.02181978,  0.03235393, -0.01071831,  0.02314097, -0.01425048],
       [-0.02670188, -0.03150516, -0.01471752,  0.03842708,  0.04261872,
        -0.00446407,  0.01001935, -0.04047058, -0.01021295,  0.04767598],
       [ 0.01091282,  0.02706928, -0.03043067, -0.02053547, -0.04147319,
        -0.04917781,  0.02045257, -0.01760782, -0.01277371, -0.01173519],
       [ 0.02886509,  0.0355274 , -0.04837899, -0.03025631,  0.01605016,
        -0.04099401, -0.01037041, -0.0284326 , -0.02554982,  0.00790708],
       [-0.00437088, -0.0269928 , -0.0184515 , -0.03135893, -0.01692337,
        -0.03447771, -0.00277464, -0.02079803,  0.01494744, -0.02303338],
       [-0.00437088, -0.0269928 , -0.0184515 , -0.03135893, -0.01692337,
        -0.03447771, -0.00277464, -0.02079803,  0.01494744, -0.02303338],
       [-0.00437088, -0.0269928 , -0.0184515 , -0.03135893, -0.01692337,
        -0.03447771, -0.00277464, -0.02079803

In [20]:
embedded_docs[0]

array([  37,  427, 9913, 1754,    0,    0,    0,    0], dtype=int32)

In [21]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 57ms/step
[[[-3.24085727e-02  1.99853294e-02  4.07472886e-02  4.97225560e-02
   -3.20636779e-02 -2.18197834e-02  3.23539265e-02 -1.07183084e-02
    2.31409706e-02 -1.42504796e-02]
  [-2.67018806e-02 -3.15051563e-02 -1.47175193e-02  3.84270810e-02
    4.26187180e-02 -4.46406752e-03  1.00193508e-02 -4.04705778e-02
   -1.02129467e-02  4.76759784e-02]
  [ 1.09128244e-02  2.70692818e-02 -3.04306746e-02 -2.05354691e-02
   -4.14731875e-02 -4.91778143e-02  2.04525702e-02 -1.76078193e-02
   -1.27737150e-02 -1.17351897e-02]
  [ 2.88650878e-02  3.55273969e-02 -4.83789928e-02 -3.02563068e-02
    1.60501637e-02 -4.09940109e-02 -1.03704110e-02 -2.84325965e-02
   -2.55498178e-02  7.90708140e-03]
  [-4.37087938e-03 -2.69927979e-02 -1.84515007e-02 -3.13589349e-02
   -1.69233680e-02 -3.44777107e-02 -2.77464464e-03 -2.07980275e-02
    1.49474405e-02 -2.30333805e-02]
  [-4.37087938e-03 -2.69927979e-02 -1.84515007e-02 -3.13589349e-02
   -1.69233680e-02 -3.44777107e

In [22]:
### Assignment

sentences=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [23]:
sentences

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [24]:
voc_size=5000

In [25]:
onehot_repr=[one_hot(words,voc_size)for words in sentences] 
print(onehot_repr)

[[3944, 4254, 4254, 3087, 2952, 1209], [4579, 2323, 4254, 912, 3861, 4848], [1148, 3735, 3975, 2675], [3944, 4865, 4254, 4015, 3944, 2928], [2681, 4595, 4786, 4254, 912, 3861, 4848], [4439, 4254, 912, 3861, 4722, 1492]]


In [27]:
sent_length=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3944 4254 4254 3087 2952 1209]
 [   0    0    0    0 4579 2323 4254  912 3861 4848]
 [   0    0    0    0    0    0 1148 3735 3975 2675]
 [   0    0    0    0 3944 4865 4254 4015 3944 2928]
 [   0    0    0 2681 4595 4786 4254  912 3861 4848]
 [   0    0    0    0 4439 4254  912 3861 4722 1492]]
